// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlowApp.Data;

#nullable disable

namespace TaskFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420171334_RenameSeededUsers")]
    partial class RenameSeededUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TaskFlowApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Учёба"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Работа"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Личное"
                        });
                });

            modelBuilder.Entity("TaskFlowApp.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Deadline = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Собрать результаты и оформить пояснительную записку.",
                            Status = "In Progress",
                            Title = "Подготовить отчёт по лабораторной",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Deadline = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Провести ревью задач и уточнить сроки выполнения.",
                            Status = "New",
                            Title = "Проверить задачи команды",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Deadline = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Подготовить базовый регламент резервного копирования базы данных.",
                            Status = "Done",
                            Title = "Настроить резервное копирование",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TaskFlowApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Администратор системы",
                            RegisteredAt = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Менеджер проектов",
                            RegisteredAt = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Manager",
                            UserName = "manager"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Кофтоногов Вадим",
                            RegisteredAt = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "User",
                            UserName = "ivan"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Виктор Пупкин",
                            RegisteredAt = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "User",
                            UserName = "maria"
                        });
                });

            modelBuilder.Entity("TaskFlowApp.Models.Task", b =>
                {
                    b.HasOne("TaskFlowApp.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskFlowApp.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskFlowApp.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskFlowApp.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
